1. What is a Tensor?

At its core, a tensor is a data structure used in PyTorch (and other deep learning frameworks) to store data. This data can be anything from a single number (a scalar, or 0-dimensional tensor), to a list of numbers (a vector, or 1-dimensional tensor), a table of numbers (a matrix, or 2-dimensional tensor), or even higher-dimensional arrays (like images, which are often 3D or 4D tensors).

In [19]:
import torch
import numpy as np

Tensor represents a Mulidimensional array of numerical Values. In one dimensional case i.e when only one axis is needed for the data, a tensor is called a vector.

With two axes, a tensor is called a matrix.
and with k> 2 axes , we just call themm kth- order tensor.


In [23]:
## Creating a Tensor from python list or Numpy Arrays

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f'Tensor from Python list:\n{x_data}')
print(f'Type: {type(x_data)}\n, Shape: {x_data.shape}, Dtype: {x_data.dtype}')

Tensor from Python list:
tensor([[1, 2],
        [3, 4]])
Type: <class 'torch.Tensor'>
, Shape: torch.Size([2, 2]), Dtype: torch.int64


In [24]:
## numpy array from the same list:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f'Tensor from Numpy array:\n{x_np}')
print(f'Type: {type(x_np)}\n, Shape: {x_np.shape}, Dtype: {x_np.dtype}')

Tensor from Numpy array:
tensor([[1, 2],
        [3, 4]])
Type: <class 'torch.Tensor'>
, Shape: torch.Size([2, 2]), Dtype: torch.int64


In [25]:
# 2.2. Creating Tensors with Specific Properties (Size, Data Type)

x_ones = torch.ones_like(x_data)
print(f'Tensor of ones with same shape as x_data:\n{x_ones}')
print(f'Type: {type(x_ones)}\n, Shape: {x_ones.shape}, Dtype: {x_ones.dtype}')

Tensor of ones with same shape as x_data:
tensor([[1, 1],
        [1, 1]])
Type: <class 'torch.Tensor'>
, Shape: torch.Size([2, 2]), Dtype: torch.int64


In [26]:
# Tensor of random values (same shape)
x_rand = torch.rand_like(x_data, dtype=torch.float) # Overrides the datatype to float
print(f"Tensor of random values (like x_data, float):\n{x_rand}\n")


Tensor of random values (like x_data, float):
tensor([[0.3465, 0.8846],
        [0.1156, 0.8616]])



In [27]:
## Creating a tensor with specific shpae directly
shape = (2, 3)  # Shape of the tensor
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor = torch.rand(shape)

print(f'Tensor of ones with shape {shape}:\n{ones_tensor}')
print(f'Tensor of zeros with shape {shape}:\n{zeros_tensor}')
print(f'Tensor of random values with shape {shape}:\n{rand_tensor}')

Tensor of ones with shape (2, 3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor of zeros with shape (2, 3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Tensor of random values with shape (2, 3):
tensor([[0.8408, 0.9410, 0.8698],
        [0.9990, 0.3734, 0.8037]])


In [28]:
# Tensors have useful attributes like shape, data type (dtype), and device.

tensor = torch.ones(4, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Data type of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}\n") # By default, it's 'cpu'

Shape of tensor: torch.Size([4, 4])
Data type of tensor: torch.float32
Device tensor is stored on: cpu



Self-Check 1:

Try creating a tensor of shape (3, 2) filled with all zeros.

What's the difference between torch.tensor() and torch.ones_like()?

In [29]:
shapes_zeros= torch.zeros(3,2)
print(f"Shape of zeros tensor: {shapes_zeros.shape}")
print(f"Data type of zeros tensor: {shapes_zeros.dtype}")
print(f"Device of zeros tensor: {shapes_zeros.device}\n") # By
print(f'Tensor of shape (3,2) with zeros:\n{shapes_zeros}')

Shape of zeros tensor: torch.Size([3, 2])
Data type of zeros tensor: torch.float32
Device of zeros tensor: cpu

Tensor of shape (3,2) with zeros:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [32]:
## Difference between torch.tensor() and torch.ones_like() is that 
'''
torch.tensor() creates a new tensor with the specified data, while
torch.ones_like() creates a new tensor filled with ones that has the same shape and data type
as the input tensor.
'''

'\ntorch.tensor() creates a new tensor with the specified data, while\ntorch.ones_like() creates a new tensor filled with ones that has the same shape and data type\nas the input tensor.\n'

In [2]:
x = torch.arange(12, dtype= torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Each of these values is called an element of the tensor.

The tensor x contains 12 elements and we can inspect total no of elements in a tensor via its *numel* method.

In [3]:
x.numel()

12

In [4]:
x.shape

torch.Size([12])

In [5]:
## Reshaping the tnesor:
X= x.reshape(3,4) ## 3,4 is possible because 3*4=12 and we had 12 elements in x
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
X.shape

torch.Size([3, 4])

In [7]:
## supposw we don't know the number of rows, but we know the number of columns:
X = x.reshape(-1, 4)  # -1 means "infer this dimension"
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
## It worked because 12 elements can be reshaped into 3 rows and 4 columns.
X.shape

torch.Size([3, 4])

## Some times we need tensor to be initialized with all 0's or 1's 

In [9]:
torch.zeros((3,2,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((3,2,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
## Often we wish to sample each element randomly from a given probability distribution.
torch.randn(3,4) # Random numbers from a normal distribution with mean 0 and variance 1


tensor([[ 0.8552,  0.3204,  0.9229,  0.4613],
        [-1.8338,  0.4313, -0.5318, -0.8995],
        [ 0.9290,  0.0437, -0.8232,  0.8999]])

In [12]:
## We can also create a tensors by supplying the exact values for each element:
custom_tensor=torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
custom_tensor



tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [13]:
custom_tensor.shape

torch.Size([3, 4])

## Indexing and Slicing
As with Python lists, we can access tensor elements by indexing (starting with 0). To access
an element based on its position relative to the end of the list, we can use negative indexing.
Finally, we can access whole ranges of indices via slicing (e.g., X[start:stop]), where
the returned value includes the first index (start) but not the last (stop).

In [14]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [16]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [17]:
## writing elements of matrix:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
X[:2, :] = 12 ## all rows up to but not including row 2 and all the columns
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## Common Tensor Operations

In [33]:
print("--- Tensor Operations ---")


--- Tensor Operations ---


In [34]:
## example tensor to be created.
tensor= torch.ones(4,4)
print(f"Original Tensor:\n{tensor}\n")

Original Tensor:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])



In [35]:
## Arithmetic operations

# Element-wise addition
tensor_add = tensor +2
print(f"Element-wise addition (tensor + 2):\n{tensor_add}\n")

Element-wise addition (tensor + 2):
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])



In [37]:
## Element-wise multiplication
tensor_mul = tensor * 3
print(f"Element-wise multiplication (tensor * 3):\n{tensor_mul}\n")

Element-wise multiplication (tensor * 3):
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])



In [38]:
## Scalar Multiplication
scalar_multiplication = tensor * 2
print(f"Scalar multiplication (tensor * 2):\n{scalar_multiplication}\n")
## same as element-wise multiplication

Scalar multiplication (tensor * 2):
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])



## Matrix Multiplication

In [40]:
# For matrix multiplication, ensure dimensions are compatible.
# (n, m) @ (m, p) -> (n, p)
tensor_A = torch.tensor([[1, 2], [3, 4]])
tensor_B = torch.tensor([[5, 6], [7, 8]])
print(f"Tensor A:\n{tensor_A}\n")
print(f"Tensor B:\n{tensor_B}\n")

Tensor A:
tensor([[1, 2],
        [3, 4]])

Tensor B:
tensor([[5, 6],
        [7, 8]])



In [41]:
## Check the shapes of the tensors before multiplication
print(f"Shape of Tensor A: {tensor_A.shape}")
print(f"Shape of Tensor B: {tensor_B.shape}\n")

Shape of Tensor A: torch.Size([2, 2])
Shape of Tensor B: torch.Size([2, 2])



In [42]:
## matches the condition for matrix multiplication i.e mxn @ nxp -> mxp
tensor_mul_mat = torch.matmul(tensor_A, tensor_B)
print(f"Matrix multiplication (A @ B):\n{tensor_mul_mat}\n")

Matrix multiplication (A @ B):
tensor([[19, 22],
        [43, 50]])



In [43]:
tensor_mul_mat = tensor_A @ tensor_B  # Using the @ operator for matrix multiplication
print(f"Matrix multiplication (A @ B):\n{tensor_mul_mat}\n")

Matrix multiplication (A @ B):
tensor([[19, 22],
        [43, 50]])



In [44]:
# In-place operations (denoted by a trailing underscore '_')
# These operations modify the tensor directly without creating a new one.

print(f"Original Tensor before in-place operation:\n{tensor}\n")
tensor.add_(2) # Adds 2 to each element in-place
print(f"Tensor after in-place addition (tensor.add_(2)):\n{tensor}\n")

Original Tensor before in-place operation:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Tensor after in-place addition (tensor.add_(2)):
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])



In [46]:
# 3.2. Indexing and Slicing
# Tensors can be indexed and sliced just like NumPy arrays or Python lists.

tensor = torch.rand(4, 4)
print(f"Random Tensor for indexing:\n{tensor}\n")



Random Tensor for indexing:
tensor([[0.6789, 0.2120, 0.8864, 0.9112],
        [0.6824, 0.7148, 0.5188, 0.5017],
        [0.0067, 0.6525, 0.9039, 0.4577],
        [0.1572, 0.2909, 0.2554, 0.0124]])



In [49]:
shape= tensor.shape
print(f'Shape of the tensor: {shape}\n')

Shape of the tensor: torch.Size([4, 4])



In [48]:
# Get the first row of the tensor
first_row = tensor[0]
print(f"First row of the tensor:\n{first_row}\n")

First row of the tensor:
tensor([0.6789, 0.2120, 0.8864, 0.9112])



In [50]:
## Getting the last column of the tensor
last_col = tensor[:, -1]
print(f"Last column of the tensor:\n{last_col}\n")

Last column of the tensor:
tensor([0.9112, 0.5017, 0.4577, 0.0124])



In [51]:
## Get a specific element ( e.g element at row 1, column 2)
specific_element = tensor[1, 2]
print(f"Element at row 1, column 2: {specific_element}\n")

Element at row 1, column 2: 0.5188109874725342



In [52]:
## slicing a sub-section
sub_tensor = tensor[0:2, 1: ]
print(f"Sub-tensor (first two rows, all columns from second onward):\n{sub_tensor}\n")

Sub-tensor (first two rows, all columns from second onward):
tensor([[0.2120, 0.8864, 0.9112],
        [0.7148, 0.5188, 0.5017]])



In [53]:
# 3.3. Reshaping Tensors
# `view()` and `reshape()` are used to change the shape of a tensor.
# `view()` requires the new tensor to share the same underlying data with the original.
# `reshape()` can return a copy if the original tensor is not contiguous in memory.

tensor = torch.arange(9) # Creates a tensor [0, 1, ..., 8]
print(f"Original tensor (1D): {tensor}")

# Reshape to a 3x3 matrix
reshaped_tensor = tensor.view(3, 3) # Or `tensor.reshape(3, 3)`
print(f"Reshaped to 3x3:\n{reshaped_tensor}\n")



Original tensor (1D): tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
Reshaped to 3x3:
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])



In [54]:
# Flattening a tensor (e.g., for input to a fully connected layer)
flattened_tensor = reshaped_tensor.view(-1) # -1 infers the dimension
print(f"Flattened tensor: {flattened_tensor}\n")


Flattened tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])



In [56]:
flattened_tensor = reshaped_tensor.flatten()  # Another way to flatten
print(f"Flattened tensor using flatten(): {flattened_tensor}\n")

Flattened tensor using flatten(): tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])



In [55]:
# Transposing a tensor (swapping dimensions)
transposed_tensor = reshaped_tensor.T # Also `reshaped_tensor.transpose(0, 1)`
print(f"Transposed tensor:\n{transposed_tensor}\n")

Transposed tensor:
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])



## Self-Check 2:

1. Create two 2
*times2* tensors, A and B, with values of your choice.
2. Perform element-wise multiplication on A and B.
3. Perform matrix multiplication on A and B.
4. Given a tensor `t = torch.arange(12).reshape(3, 4)`, how would you select the second row and the third column?

In [57]:
## Creating a Tensor with a specific size and data type
tensor_A= torch.randn(2,2, dtype= torch.float32)  # Random tensor with float32 type
print(f"Tensor A with specific size and dtype:\n{tensor_A}\n")
tensor_B = torch.randn(2, 2, dtype=torch.float64)  # Random tensor with float64 type
print(f"Tensor B with specific size and dtype:\n{tensor_B}\n")

Tensor A with specific size and dtype:
tensor([[ 1.7439, -1.0478],
        [ 1.3917, -0.9843]])

Tensor B with specific size and dtype:
tensor([[-0.3332, -0.1754],
        [ 0.2403,  0.8403]], dtype=torch.float64)



In [60]:
## Element-wise multiplication of tensor A and B
## Note: The tensors must have the same shape for element-wise operations.
elementwise_mul = tensor_A * tensor_B
print(f"Element-wise multiplication of Tensor A and B:\n{elementwise_mul}\n")

Element-wise multiplication of Tensor A and B:
tensor([[-0.5811,  0.1838],
        [ 0.3344, -0.8271]], dtype=torch.float64)



In [62]:
## Matrix multiplication of tensor A and B
matrix_mul = torch.matmul(tensor_A, tensor_B.to(tensor_A.dtype))  # Ensure dtype compatibility
print(f"Matrix multiplication of Tensor A and B:\n{matrix_mul}\n")

Matrix multiplication of Tensor A and B:
tensor([[-0.8329, -1.1864],
        [-0.7003, -1.0713]])



In [63]:
# Given a tensor `t = torch.arange(12).reshape(3, 4)`, how would you select the second row and the third column?
t = torch.arange(12).reshape(3, 4)
print(f"Original tensor t:\n{t}\n")

Original tensor t:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])



In [64]:
## selecting second row and the third column.

selected= t[1, 2]  # Indexing starts at 0, so this is the second row and third column
print(f"Selected element (second row, third column): {selected}\n")

Selected element (second row, third column): 6



## 4. Device Management (CPU vs. GPU)

One of the most powerful features of PyTorch is its ability to seamlessly move computations to a GPU (Graphics Processing Unit) when available. GPUs are highly parallel processors, making them ideal for the massive parallel computations required in deep learning.

In [65]:
print("--- Device Management ---")
# Tensors can be moved between CPU and GPU for faster computation.
if torch.cuda.is_available():
    device = torch.device('cuda') # Use GPU if available
else:
    device = torch.device('cpu')
print(f"Using device: {device}\n")

--- Device Management ---
Using device: cpu



In [66]:
# Move a tensor to the specified device
tensor_on_cpu = torch.tensor([1, 2, 3])
print(f"Tensor on CPU: {tensor_on_cpu.device}")


Tensor on CPU: cpu


In [67]:
tensor_on_device = tensor_on_cpu.to(device)
print(f"Tensor on {device}: {tensor_on_device.device}\n")


Tensor on cpu: cpu



In [72]:
# Operations between tensors must be on the same device
tensor_A_gpu = torch.rand(2, 2).to(device)
tensor_B_gpu = torch.rand(2, 2).to(device)

if device == "cuda":
    result_gpu = tensor_A_gpu + tensor_B_gpu
    print(f"Result of operation on GPU:\n{result_gpu}\n")
else:
    print("GPU not available, operations remain on CPU.\n")
result_gpu= tensor_A_gpu + tensor_B_gpu

GPU not available, operations remain on CPU.



In [73]:
# Moving back to CPU (useful for operations that require CPU, like converting to NumPy)
result_cpu = result_gpu.to("cpu")
print(f"Result moved back to CPU:\n{result_cpu}\n")

Result moved back to CPU:
tensor([[1.4838, 0.6265],
        [0.1455, 0.7708]])



In [74]:
# Converting a PyTorch tensor to a NumPy array (requires tensor to be on CPU)
np_array_from_tensor = result_cpu.numpy()
print(f"NumPy array from tensor:\n{np_array_from_tensor}\n")

NumPy array from tensor:
[[1.4837785  0.626454  ]
 [0.14545876 0.77075356]]



In [75]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [76]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [78]:
## Element-wise operations on tensors
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [79]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [80]:
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [81]:
torch.cat((X, Y), dim =0), torch.cat((X, Y), dim = 1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [82]:
X == Y  # Element-wise comparison

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [83]:
X.sum()

tensor(66.)

## Broadcasting
By now, you know how to perform elementwise binary operations on two tensors of the
same shape. Under certain conditions, even when shapes differ, we can still perform ele-
mentwise binary operations by invoking the broadcasting mechanism. Broadcasting works
according to the following two-step procedure: 

(i) expand one or both arrays by copying
elements along axes with length 1 so that after this transformation, the two tensors have the
same shape; 

(ii) perform an elementwise operation on the resulting arrays.

In [84]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [86]:
a + b # Broadcasting: a is broadcasted to shape (3, 2) and b to shape (3, 2) by repeating their values.

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## Saving Memory

Running operations can cause new memory to be allocated to host results. For example, if
we write `Y = X + Y`, we dereference the tensor that Yused to point to and instead point Yat
the newly allocated memory. We can demonstrate this issue with Python’s id() function,
which gives us the exact address of the referenced object in memory. Note that after we
run `Y = Y + X`, `id(Y)`points to a different location. That is because Python first evaluates
`Y + X`, allocating new memory for the result and then points Y to this new location in
memory.

In [88]:
before = id(Y)
Y = Y + X  # This creates a new tensor and assigns it to Y
after = id(Y)
print(f"ID before operation: {before}, ID after operation: {after}\n")

ID before operation: 5351399952, ID after operation: 5351400672



In [89]:
before == after  # This will be False, as Y now points to a new tensor

False

This might be undesirable for two reasons. First, we do not want to run around allocat-
ing memory unnecessarily all the time. In machine learning, we often have hundreds of
megabytes of parameters and update all of them multiple times per second. Whenever
possible, we want to perform these updates in place. Second, we might point at the same
parameters from multiple variables. If we do not update in place, we must be careful to
update all of these references, lest we spring a memory leak or inadvertently refer to stale
parameters.

Fortunately, performing in-place operations is easy. We can assign the result of an oper-
ation to a previously allocated array Y by using slice notation: `Y[:] = <expression>`.
To illustrate this concept, we overwrite the values of tensor Z, after initializing it, using
zeros_like, to have the same shape as Y.

In [92]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 5351542048
id(Z): 5351542048


In [93]:
before = id(X)
X += Y
id(X) == before

True

## Conversion to Other Python Objects

In [94]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [95]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# Data Preprocessing


## Reading the Dataset

In [98]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok = True)
data_file = os.path.join('..', 'data', 'housing_tiny.csv')

with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [99]:
import pandas as pd
data = pd.read_csv(data_file)
data

NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000

In [100]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs= pd.get_dummies(inputs, dummy_na = True)
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True


In [101]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True


In [102]:
import torch
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))